<?php
/**
 * Dock Configuration
 * Included as part of `partials/settings.php`
 *
 * @var array $tooltips Tooltip copy map
 * @var string $defaultTooltipMessage Default tooltip fallback message
 * @var array<string, mixed> $config
 */

renderAccordionSectionStart(
	'dock-config',
	renderHeading( 'Dock Configuration' ),
	[
		'expanded'  => false,
		'caretPath' => $config['paths']['assets'] . '/images/caret-down.svg',
	]
);
?>
<div class="settings-container">
	<div id="dock-config-editor">
		<ul id="dock-list"><!-- Generated by dock.js --></ul>
		<button type="button" id="add-dock-item">➕ Add Dock Item</button>
	</div>
	<input type="hidden" id="dock_json_input" name="dock_json">
</div>
<?php renderButtonBlock( [ 'label' => 'Save Settings', 'type' => 'submit' ] ); ?>

<?php renderAccordionSectionEnd(); ?>
