<?php
/**
 * Folders Configuration
 * Included as part of `partials/settings.php`
 *
 * @var array $tooltips Tooltip copy map
 * @var string $defaultTooltipMessage Default tooltip fallback message
 * @var array<string, mixed> $config
 */

renderAccordionSectionStart(
	'folders-config',
	renderHeading( 'Folders Configuration' ),
	[
		'expanded'  => false,
		'caretPath' => $config['paths']['assets'] . '/images/caret-down.svg',
	]
);
?>
<div class="settings-container">
	<div id="folders-config">
		<ul id="folders-config-list" class="draggable-list"><!-- Generated by folders.js --></ul>
		<button type="button" id="add-folder-column">➕ Add Folder Column</button>
	</div>
	<input type="hidden" id="folders_json_input" name="folders_json">
</div>
<?php renderButtonBlock( [ 'label' => 'Save Settings', 'type' => 'submit' ] ); ?>

<?php renderAccordionSectionEnd(); ?>
