<?php
/**
 * Link Templates Configuration
 * Included as part of `partials/settings.php`
 *
 * @var array $tooltips Tooltip copy map
 * @var string $defaultTooltipMessage Default tooltip fallback message
 * @var array<string, mixed> $config
 */

renderAccordionSectionStart(
	'link-templates-config',
	renderHeading( 'Link Templates' ),
	[
		'expanded'  => false,
		'caretPath' => $config['paths']['assets'] . '/images/caret-down.svg',
	]
);
?>
<div class="settings-container">
	<div id="link-templates-config">
		<p id="link-templates-help">
			Build your folder link templates with plain HTML. Use
			<code>{urlName}</code> wherever the site name should appear — in text
			or in attributes.<br>
			<!-- Currently supported variables: <code>{urlName}</code>.<br> -->
			Example:
			<code>&lt;li class='folder-item'&gt;&lt;a href='https://local.{urlName}.com'&gt;{urlName}&lt;/a&gt;&lt;/li&gt;</code>.<br>
			Tips: Tab to indent, Shift+Tab to outdent, Enter preserves current indent.
		</p>
		<p id="editor-instructions" class="sr-only">
			When inside the editor, press Tab to insert a tab character. Press Escape, then Tab to move
			focus
			out of the editor.
		</p>

		<?php renderSeparatorLine( 'sm' ) ?>

		<ul
				id="link-templates-list"
				class="template-list"
				aria-describedby="link-templates-help"
				aria-live="polite"
		><!-- Generated by linkTemplates.js --></ul>
		<button type="button" id="add-link-template">➕ Add Link Template</button>
	</div>
	<input type="hidden" id="link_templates_json_input" name="link_templates_json" value="">
</div>
<?php renderButtonBlock( [ 'label' => 'Save Settings', 'type' => 'submit' ] ); ?>

<?php renderAccordionSectionEnd(); ?>
